column_width = 128
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4  
quote_style = "AutoPreferDouble"
call_parentheses = "NoSingleTable"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false