[package]
name = "author/project-name"
version = "0.0.0"
authors = ["author"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[dependencies]
base64 = "reselim/base64@3.0.0"
signal = "sleitnick/signal@2.0.1"